------------------------------------------------------
-- Autor       : NTT Data Centers - Sevilla
-- Descripción : Java - JDBC - Oracle - Taller 1
-- Responsable : Agustín Guerrero Reyes
------------------------------------------------------

-- Borrado previo.

DROP TABLE NTTDATA_ORACLE_AUTHORS;
DROP SEQUENCE NTTDATA_ORACLE_AUTHORS_SEQ;
DROP TABLE NTTDATA_ORACLE_BOOKS;
DROP SEQUENCE NTTDATA_ORACLE_BOOKS_SEQ;

-- Creación tabla de autores.

CREATE TABLE NTTDATA_ORACLE_AUTHORS (

    ID INT NOT NULL,
    NAME VARCHAR(100),
    SURNAME VARCHAR(200),
    BIRTH_DATE DATE,
    COUNTRY VARCHAR(200),
    
    CONSTRAINT PK_ID_AUTHORS PRIMARY KEY (ID)

);

-- Descripción de las columnas de la tabla autores.

COMMENT ON COLUMN "NTTDATA_ORACLE_AUTHORS"."ID" IS 'ID DEL AUTOR';
COMMENT ON COLUMN "NTTDATA_ORACLE_AUTHORS"."NAME" IS 'NOMBRE DEL AUTOR';
COMMENT ON COLUMN "NTTDATA_ORACLE_AUTHORS"."SURNAME" IS 'APELLIDO/S DEL AUTOR';
COMMENT ON COLUMN "NTTDATA_ORACLE_AUTHORS"."BIRTH_DATE" IS 'FECHA DE NACIMIENTO DEL AUTOR';
COMMENT ON COLUMN "NTTDATA_ORACLE_AUTHORS"."COUNTRY" IS 'PAÍS DEL AUTOR';

-- Secuencia que asociada a la tabla autores.

CREATE SEQUENCE  "NTTDATA_ORACLE_AUTHORS_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;

-- Inserción de autores.

INSERT INTO NTTDATA_ORACLE_AUTHORS (ID, NAME, SURNAME, BIRTH_DATE, COUNTRY)
VALUES (NTTDATA_ORACLE_AUTHORS_SEQ.NEXTVAL, 'Arturo', 'Pérez Reverte', '25/11/1951', 'España');
INSERT INTO NTTDATA_ORACLE_AUTHORS (ID, NAME, SURNAME, BIRTH_DATE, COUNTRY)
VALUES (NTTDATA_ORACLE_AUTHORS_SEQ.NEXTVAL, 'Santiago', 'Posteguillo', '01/01/1967', 'España');
INSERT INTO NTTDATA_ORACLE_AUTHORS (ID, NAME, SURNAME, BIRTH_DATE, COUNTRY)
VALUES (NTTDATA_ORACLE_AUTHORS_SEQ.NEXTVAL, 'Juan', 'Eslava Galán', '07/03/1948', 'España');
INSERT INTO NTTDATA_ORACLE_AUTHORS (ID, NAME, SURNAME, BIRTH_DATE, COUNTRY)
VALUES (NTTDATA_ORACLE_AUTHORS_SEQ.NEXTVAL, 'John Ronald Reuel', 'Tolkien', '03/01/1892', 'Reino Unido');
INSERT INTO NTTDATA_ORACLE_AUTHORS (ID, NAME, SURNAME, BIRTH_DATE, COUNTRY)
VALUES (NTTDATA_ORACLE_AUTHORS_SEQ.NEXTVAL, 'Ken', 'Follett', '05/06/1949', 'Reino Unido');
INSERT INTO NTTDATA_ORACLE_AUTHORS (ID, NAME, SURNAME, BIRTH_DATE, COUNTRY)
VALUES (NTTDATA_ORACLE_AUTHORS_SEQ.NEXTVAL, 'Joël', 'Dicker', '16/06/1985', 'Suiza');
INSERT INTO NTTDATA_ORACLE_AUTHORS (ID, NAME, SURNAME, BIRTH_DATE, COUNTRY)
VALUES (NTTDATA_ORACLE_AUTHORS_SEQ.NEXTVAL, 'Alexandre', 'Dumas', '24/07/1802', 'Francia');
INSERT INTO NTTDATA_ORACLE_AUTHORS (ID, NAME, SURNAME, BIRTH_DATE, COUNTRY)
VALUES (NTTDATA_ORACLE_AUTHORS_SEQ.NEXTVAL, 'Fiódor', 'Dostoyevski', '11/11/1821', 'Rusia');



-- Creación tabla libros.

CREATE TABLE NTTDATA_ORACLE_BOOKS (

    ID INT NOT NULL,
    ISBN VARCHAR(200) NOT NULL UNIQUE,
    TITLE VARCHAR(200),
    EDITORIAL VARCHAR(200),
    EDITION_YEAR VARCHAR(4),
    YEAR VARCHAR(4),
    ID_AUTHOR INT NOT NULL,
    
    CONSTRAINT PK_ID_BOOKS PRIMARY KEY (ID),
    CONSTRAINT FK_ID_AUTHOR_BOOKS FOREIGN KEY (ID_AUTHOR) REFERENCES NTTDATA_ORACLE_AUTHORS (ID)

);

-- Descripción de las columnas de la tabla libros.

COMMENT ON COLUMN "NTTDATA_ORACLE_BOOKS"."ID" IS 'ID DEL LIBRO';
COMMENT ON COLUMN "NTTDATA_ORACLE_BOOKS"."ISBN" IS 'CÓDIGO ISBN DEL LIBRO';
COMMENT ON COLUMN "NTTDATA_ORACLE_BOOKS"."TITLE" IS 'TÍTULO DEL LIBRO';
COMMENT ON COLUMN "NTTDATA_ORACLE_BOOKS"."EDITORIAL" IS 'EDITORIAL DEL LIBRO';
COMMENT ON COLUMN "NTTDATA_ORACLE_BOOKS"."EDITION_YEAR" IS 'AÑO DE LA EDICIÓN DEL LIBRO';
COMMENT ON COLUMN "NTTDATA_ORACLE_BOOKS"."YEAR" IS 'AÑO DE PUBLICACIÓN DEL LIBRO';
COMMENT ON COLUMN "NTTDATA_ORACLE_BOOKS"."ID_AUTHOR" IS 'ID DEL AUTOR DEL LIBRO';

-- Secuencia que asociada a la tabla autores.

CREATE SEQUENCE  "NTTDATA_ORACLE_BOOKS_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;

-- Inserción de libros.

INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788420454665', 'Línea De Fuego', 'Alfaguara', '2020', '2020', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Arturo' AND SURNAME = 'Pérez Reverte'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788484502630', 'Territorio comanche', 'Debolsillo', '2021', '1994', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Arturo' AND SURNAME = 'Pérez Reverte'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788420466248', 'La tabla de Flandes', 'Alfaguara', '2003', '1990', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Arturo' AND SURNAME = 'Pérez Reverte'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788498725407', 'El hijo del cónsul', 'Ediciones B', '2011', '2006', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Santiago' AND SURNAME = 'Posteguillo'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788408103257', 'Los asesinos del emperador', 'Planeta', '2011', '2011', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Santiago' AND SURNAME = 'Posteguillo'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788408197409', 'Yo, Julia', 'Planeta', '2018', '2018', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Santiago' AND SURNAME = 'Posteguillo'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788408246596', 'En busca del unicornio', 'Planeta', '2021', '1987', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Juan' AND SURNAME = 'Eslava Galán'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788408086611', 'Los años del miedo', 'Planeta', '2011', '2008', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Juan' AND SURNAME = 'Eslava Galán'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788408175414', 'Historia de España contada para escépticos', 'Planeta', '2017', '1995', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Juan' AND SURNAME = 'Eslava Galán'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788445073803', 'El Hobbit', 'Minotauro', '2002', '1937', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'John Ronald Reuel' AND SURNAME = 'Tolkien'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788445073810', 'El Silmarillion', 'Minotauro', '2002', '1977', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'John Ronald Reuel' AND SURNAME = 'Tolkien'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788445073728', 'La Comunidad del Anillo', 'Minotauro', '2002', '1954', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'John Ronald Reuel' AND SURNAME = 'Tolkien'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788401328510', 'Los pilares de la tierra', 'Plaza And Janes Editores', '2017', '1989', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Ken' AND SURNAME = 'Follett'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788497593946', 'Un lugar llamado libertad', 'Debolsillo', '2016', '1995', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Ken' AND SURNAME = 'Follett'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788401337635', 'La caída de los gigantes', 'Plaza And Janes Editores', '2010', '2010', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Ken' AND SURNAME = 'Follett'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788420414065', 'La verdad sobre el caso Harry Quebert', 'Alfaguara', '2021', '2012', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Joël' AND SURNAME = 'Dicker'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788466355391', 'La desaparición de Stephanie Mailer', 'Debolsillo', '2021', '2018', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Joël' AND SURNAME = 'Dicker'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788466357999', 'El enigma de la habitación 622', 'Debolsillo', '2022', '2020', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Joël' AND SURNAME = 'Dicker'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788491043201', 'Los tres mosqueteros', 'Alianza Editorial', '2016', '1844', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Alexandre' AND SURNAME = 'Dumas'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788417928926', 'El conde de Montecristo', 'Plutón Ediciones', '2020', '1845', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Alexandre' AND SURNAME = 'Dumas'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788490744703', 'El tulipán negro', 'Verbum', '2017', '1850', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Alexandre' AND SURNAME = 'Dumas'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788418008122', 'Crimen y Castigo', 'Alma Europa', '2020', '1866', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Fiódor' AND SURNAME = 'Dostoyevski'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788416358083', 'El jugador', 'Sexto Piso', '2015', '1866', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Fiódor' AND SURNAME = 'Dostoyevski'));
INSERT INTO NTTDATA_ORACLE_BOOKS (ID, ISBN, TITLE, EDITORIAL, EDITION_YEAR, YEAR, ID_AUTHOR) 
VALUES (NTTDATA_ORACLE_BOOKS_SEQ.NEXTVAL, '9788413625218', 'Los hermanos Karamázov', 'Alianza Editorial', '2021', '1880', (SELECT ID FROM NTTDATA_ORACLE_AUTHORS WHERE NAME = 'Fiódor' AND SURNAME = 'Dostoyevski'));


